### ISSUE TITLE
Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by alexandremfonseca** [sopov/resumeio2pdf#10]
Hello! I've been trying to download my resume and keep receiving the same error, please find the error in the picture attached. Do you know what could be causing this?

![Error_resumeio2pdf](https://user-images.githubusercontent.com/105955493/179883939-504217da-8ad4-4f17-9f87-a3dfde31efcd.png)

**Comment by sopov** [comment]
Something is wrong on the resume.io side, 
Try opening it in a browser.
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

**Comment by sopov** [comment]
you try download with `url` as SecureID or `https://resume.io/r/url` 
correct: `go run main.go -url https://resume.io/...`
or just: `go run main.go https://resume.io/...`

**Comment by alexandremfonseca** [comment]
Thank you!
