### ISSUE TITLE
thats not an issue. I just want to say Thank you. lots of loveeeeee

### ISSUE THREAD

**Issue by adiShinwari** [sopov/resumeio2pdf#17]

**Comment by kirat-rai** [comment]
i am not able to understand the final step please help me

**Comment by kirat-rai** [comment]
![Screenshot 2023-03-09 182426](https://user-images.githubusercontent.com/89451075/224029583-b4867b41-8d94-4a98-a555-f918d8b02952.png)

**Comment by adiShinwari** [comment]
Which final step?

**Comment by kirat-rai** [comment]
after go build

**Comment by 11xjas** [comment]
> 
> ![Screenshot 2023-03-09 182426](https://user-images.githubusercontent.com/89451075/224029583-b4867b41-8d94-4a98-a555-f918d8b02952.png)
> 

try "resumeio2pdf " link"

**Comment by carlossando** [comment]
or you can just do
go run main.go https://resume.io/r/...

**Comment by nitesh2920** [comment]
> or you can just do go run main.go https://resume.io/r/...

Thank you so much but the pdf is generated in image all the text are unselectable it's no use i cannot edit it by myself or cannot copy paste the information.
