### ISSUE TITLE
I am unable to download my resume, can you please help me or download my resume https://resume.io/r/Pf6W0jCf0

### ISSUE THREAD

**Issue by tyrantsMedic** [sopov/resumeio2pdf#18]
![Screenshot 2023-03-01 004942](https://user-images.githubusercontent.com/50214329/221963358-6f1692ed-bc1c-4653-8208-aa260aff0342.png)

**Comment by tyrantsMedic** [comment]
Nvm i got it worked, thank you

**Comment by YehiaWLD** [comment]
how i have same issue
