### ISSUE TITLE
IMPORTANT!!! is it me making mistake or PDFS are just container for pictures of pages ???

### ISSUE THREAD

**Issue by KTasliel** [sopov/resumeio2pdf#25]
I just downloaded my resume with app, and it basicly downloads pictures and put inside of PDF's, in this way instead of helping you are missleading people and resulting loosing opportunity of geting hired. 

Because big or small all companies are using software robots for reading resumes. as long as this pdf is just a picture :( software can't read it. in the end you're loosing opportunity of geting hired.

**Comment by sopov** [comment]
https://resume.io/pricing
