### ISSUE TITLE
Resume.io removed share option

### ISSUE THREAD

**Issue by v1shnu-v** [sopov/resumeio2pdf#27]
Looks like resume.io has removed the share option.

**Comment by nightblure** [comment]
++

**Comment by VigneshRamanathan101** [comment]
Yes, I too noticed that.

**Comment by lemcoder** [comment]
Secure id is inside the response of `GET` request at `https://resume.io/api/app/resumes`. You can obtain it from here

**Comment by v1shnu-v** [comment]
Got it. Not sure if that can be automated since the url works only after logging in.

**Comment by VigneshRamanathan101** [comment]
After logging in I did a https://resume.io/api/app/resumes from browser and my response had "secureId": null,

**Comment by naysec01** [comment]
Unable to find secureId, is there any other options or tool does not work now anymore 

edit:
tool is still working steps:
go to https://resume.io/api/app/resumes and copy your secureid, then use it with tool
` ./resumeio2pdf -url https://resume.io/r/secureidhere`

**Comment by Anubhav990** [comment]
> Unable to find secureId, is there any other options or tool does not work now anymore
> 
> edit: tool is still working steps: go to https://resume.io/api/app/resumes and copy your secureid, then use it with tool ` ./resumeio2pdf -url https://resume.io/r/secureidhere`

thanks bro its working , I copied the secure id following the above steps and copy pasted the secure id here "https://resume.io/r/your_secure_id"  and added the final url here https://resumeio.ankanroy.in/ to generate a pdf

**Comment by Jupiter644** [comment]
my account on resume.io is new and seureId is null. what to do now??
