### ISSUE TITLE
Shows only first page

### ISSUE THREAD

**Issue by justmike1** [sopov/resumeio2pdf#3]
is there a way to use the tool to export all pages in the link?

**Comment by sopov** [comment]
It exports all pages and links and creates a PDF file in the output

**Comment by justmike1** [comment]
did you tested it with multiple pages? because it didn't work for me

**Comment by sopov** [comment]
Yes, checked again -- everything works fine.

**Comment by justmike1** [comment]
I see what is the issue, it does work, but not immediately after the change, lets's say you add a link/page or so on your CV, the script still takes old links from the cache or something, you need to wait (not sure how much time), to get a perfect result after you finish your editing.

**Comment by sopov** [comment]
The script gets the pages with the json that will be on the public page, and this is the cache you will see if you go to the web version.
