### ISSUE TITLE
2 pages are being created

### ISSUE THREAD

**Issue by ftzi** [sopov/resumeio2pdf#5]
This is what I am running:

`./resumeio2pdf -url https://resume.io/r/Kj1G9SRio -y`

**Comment by sopov** [comment]
open this link in your browser.
you only have one page.
pdf also with a single page

**Comment by ftzi** [comment]
Yes, but when I run the said line I am having a pdf with 2 pages being created. I am even having to use an online tool to only get the first page.

**Comment by sopov** [comment]
I ran it, it created with one https://dsc.cloud/5b0bee/Kj1G9SRio.pdf

**Comment by ftzi** [comment]
Now a single page is being created as expected. I have no idea on what happened before. I was having two identical pages being created.

**Comment by prateekguddad** [comment]
SrBrahma please do tell what program exactly u r running, this guy sopov is not helping me at all

**Comment by prateekguddad** [comment]
SrBrahma please do tell what program exactly u r running, this guy sopov is not helping me at all
