### ISSUE TITLE
Not understanding anything

### ISSUE THREAD

**Issue by 01fe18bcv043** [sopov/resumeio2pdf#6]
Where to write the program? What to write the program? 
I am not understanding anything, please do help me to download my resume from resume.io!!
I have installed "go"

**Comment by sopov** [comment]
https://github.com/sopov/resumeio2pdf.bin

**Comment by 01fe18bcv043** [comment]
Just download the below file without the watermark of resume.io
https://resume.io/r/pqXYyHpuf
Tell me how you download this file using the code or anything you do

**Comment by sopov** [comment]
I'm sorry, but you're just being lazy. I built a binary for you, and need only run with a link to your resume and that's it.

**Comment by 01fe18bcv043** [comment]
Where is the code? and Where to write it yaar? 
I am a Civil person, i don't know about code and all. So, i asked you to help me...please do understand
