### ISSUE TITLE
Where to write the code?

### ISSUE THREAD

**Issue by 01fe18bcv043** [sopov/resumeio2pdf#7]
Where is the code? and Where to write it yaar?
I am a Civil person, i don't know about code and all. So, i asked you to help me...please do understand

**Comment by sopov** [comment]
try googling: "how to run a program from the command line"

**Comment by 01fe18bcv043** [comment]
Where is the program for downloading the resume?

**Comment by sopov** [comment]
https://github.com/sopov/resumeio2pdf.bin

**Comment by 01fe18bcv043** [comment]
Please do share if you have any video of it in youtube

**Comment by sopov** [comment]
I don't have a video. I don't even have windows. But it should work there. Please do not create new issues.

If you don't want to figure out how it works, then I'm not in the business of teaching everyone. 

Please pay to resume.io and get PDF from a box.

**Comment by sopov** [comment]
> Why are you doing like this bro?
> Help me out to download the resume

I have a job and I have to do it, it was done as a hobby and nothing more.

if you can't figure it out, pay a couple of bucks and get better results from resume.io

**Comment by 01fe18bcv043** [comment]
I can understand it's ur hobby, but it will help lot of  people out here. 
And all of them can't pay, I hope u understand

**Comment by 01fe18bcv043** [comment]
Till now u have chated so many things, in this time u would have said the procedure to download the resume know!!!

**Comment by Johnny-Connor** [comment]
Hi, I believe technology should be accessible for everyone, no matter if they know how it works or not. Mocking people for having less knowledge than you in a certain segment is deeply immoral. Besides, it goes against the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#maintaining-a-strong-community).

For these reasons, I felt obligated to explain how to use the program here.

# Tutorial
- **Step 1:** Download the files from this repository (click the green 'Code' button and select 'Download ZIP'). Store it inside an empty file and extract your downloaded .zip there.
- **Step 2:** The program was coded in 'Go' (programming language), so to run it, you have to install 'Go' at: https://go.dev/doc/install.
- **Step 3:** Open your command prompt (cmd.exe). You can do that by searching for it in your Windows search box or by pressing 'Windows + R' and typing 'cmd.exe'.
- **Step 4:** Check if 'Go' was successfully installed by typing
```bash
go version
```
The command should show you what version you have installed in your machine.
- **Step 5:** While still on the prompt, navigate to inside the program folder. To do that, just type 'cd ' followed by the address you want to access. Example:
```bash
cd C:\Users\UserName\Downloads\NewFolder\resumeio2pdf-main
```
- **Step 6:** Inside 'resumeio2pdf-main', compile the program into an executable by typing
```bash
go build
```
- **Step 7:** Lastly, run the program by typing:
```bash
resumeio2pdf -y https://resume.io/r/YourPageID
```
- **Step 8:** Your .pdf file should be available for use inside the program's folder! 👍

**Comment by Johnny-Connor** [comment]
Hi, I believe technology should be accessible for everyone, no matter if they know how it works or not. Mocking people for having less knowledge than you in a certain segment is deeply immoral. Besides, it goes against the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#maintaining-a-strong-community).

For these reasons, I felt obligated to explain how to use the program here.

# Tutorial
- **Step 1:** Download the files from this repository (click the green 'Code' button and select 'Download ZIP'). Store it inside an empty file and extract your downloaded .zip there.
- **Step 2:** The program was coded in 'Go' (programming language), so to run it, you have to install 'Go' at: https://go.dev/doc/install.
- **Step 3:** Open your command prompt (cmd.exe). You can do that by searching for it in your Windows search box or by pressing 'Windows + R' and typing 'cmd.exe'.
- **Step 4:** Check if 'Go' was successfully installed by typing
```bash
go version
```
The command should show you what version you have installed in your machine.
- **Step 5:** While still on the prompt, navigate to inside the program folder. To do that, just type 'cd ' followed by the address you want to access. Example:
```bash
cd C:\Users\UserName\Downloads\NewFolder\resumeio2pdf-main
```
- **Step 6:** Inside 'resumeio2pdf-main', compile the program into an executable by typing
```bash
go build
```
- **Step 7:** Lastly, run the program by typing:
```bash
resumeio2pdf -y https://resume.io/r/YourPageID
```
- **Step 8:** Your .pdf file should be available for use inside the program's folder! 👍

**Comment by Johnny-Connor** [comment]
Hi, I believe technology should be accessible for everyone, no matter if they know how it works or not. Mocking people for having less knowledge than you in a certain segment is deeply immoral. Besides, it goes against [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#maintaining-a-strong-community).

For these reasons, I felt obligated to explain how to use the program here.

# Tutorial
- **Step 1:** Download the files from this repository (click the green 'Code' button and select 'Download ZIP'). Store it inside an empty file and extract your downloaded .zip there.
- **Step 2:** The program was coded in 'Go' (programming language), so to run it, you have to install 'Go' at: https://go.dev/doc/install.
- **Step 3:** Open your command prompt (cmd.exe). You can do that by searching for it in your Windows search box or by pressing 'Windows + R' and typing 'cmd.exe'.
- **Step 4:** Check if 'Go' was successfully installed by typing
```bash
go version
```
The command should show you what version you have installed in your machine.
- **Step 5:** While still on the prompt, navigate to inside the program folder. To do that, just type 'cd ' followed by the address you want to access. Example:
```bash
cd C:\Users\UserName\Downloads\NewFolder\resumeio2pdf-main
```
- **Step 6:** Inside 'resumeio2pdf-main', compile the program into an executable by typing
```bash
go build
```
- **Step 7:** Lastly, run the program by typing:
```bash
resumeio2pdf -y https://resume.io/r/YourPageID
```
- **Step 8:** Your .pdf file should be available for use inside the program's folder! 👍

**Comment by Johnny-Connor** [comment]
Hi, I believe technology should be accessible for everyone, no matter if they know how it works or not. Mocking people for having less knowledge than you in a certain segment is deeply immoral. Besides, it goes against [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#maintaining-a-strong-community).

For these reasons, I felt obligated to explain how to use the program here.

# Tutorial
- **Step 1:** Download the files from this repository (click the green 'Code' button and select 'Download ZIP'). Store it inside an empty file and extract your downloaded .zip file there.
- **Step 2:** The program was coded in 'Go' (programming language), so to run it, you have to install 'Go' at: https://go.dev/doc/install.
- **Step 3:** Open your command prompt (cmd.exe). You can do that by searching for it in your Windows search box or by pressing 'Windows + R' and typing 'cmd.exe'.
- **Step 4:** Check if 'Go' was successfully installed by typing
```bash
go version
```
The command should show you what version you have installed in your machine.
- **Step 5:** While still on the prompt, navigate to inside the program's folder. To do that, just type 'cd ' followed by the address you want to access. Example:
```bash
cd C:\Users\UserName\Downloads\NewFolder\resumeio2pdf-main
```
- **Step 6:** Inside 'resumeio2pdf-main', compile the program into an executable by typing
```bash
go build
```
- **Step 7:** Lastly, run the generated 'resumeio2pdf' .exe file alongside its commands by typing:
```bash
resumeio2pdf -y https://resume.io/r/YourPageID
```
- **Step 8:** Your .pdf file should be available for use inside the program's folder! 👍
